<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Yeager" failures="0" tests="3" name="AnkitSeleniumLearning.Tests.ErrorValidations" time="0.016" errors="1" timestamp="2024-02-23T16:27:46 IST" skipped="2">
  <testcase classname="AnkitSeleniumLearning.Tests.ErrorValidations" name="loginErrorValidation" time="0.000">
    <error message="Cannot invoke &quot;AnkitSeleniumLearning.pageObjects.LandingPage.loginApplication(String, String)&quot; because &quot;this.landingPage&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "AnkitSeleniumLearning.pageObjects.LandingPage.loginApplication(String, String)" because "this.landingPage" is null
at AnkitSeleniumLearning.Tests.ErrorValidations.loginErrorValidation(ErrorValidations.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
    </error>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="AnkitSeleniumLearning.Tests.ErrorValidations" name="loginErrorValidation" time="0.016">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="AnkitSeleniumLearning.Tests.ErrorValidations" name="loginErrorValidation" time="0.000">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
</testsuite> <!-- AnkitSeleniumLearning.Tests.ErrorValidations -->
